package com.saurav.agentic.models;

/**
 * ApiTestCase - Represents a single API test case
 * Generated by Agent 5B from discovered endpoints
 * Saved to api-test-cases.xlsx
 */
public class ApiTestCase {

    private String testCaseId;
    private String testCaseName;
    private String endpoint;
    private String method;
    private String requestBody;
    private String requestParams;
    private String expectedStatusCode;
    private String expectedResponseField;
    private String assertionType;     // STATUS_CODE, FIELD_EXISTS, FIELD_VALUE,
                                      // RESPONSE_TIME, CONTENT_TYPE, SCHEMA
    private String testType;          // Positive, Negative, Edge
    private String priority;          // High, Medium, Low
    private String description;
    private boolean automationFeasible;

    public ApiTestCase() {}

    // ── Getters ───────────────────────────────────────────────────────────────
    public String getTestCaseId()            { return testCaseId; }
    public String getTestCaseName()          { return testCaseName; }
    public String getEndpoint()              { return endpoint; }
    public String getMethod()                { return method; }
    public String getRequestBody()           { return requestBody; }
    public String getRequestParams()         { return requestParams; }
    public String getExpectedStatusCode()    { return expectedStatusCode; }
    public String getExpectedResponseField() { return expectedResponseField; }
    public String getAssertionType()         { return assertionType; }
    public String getTestType()              { return testType; }
    public String getPriority()              { return priority; }
    public String getDescription()           { return description; }
    public boolean isAutomationFeasible()    { return automationFeasible; }

    // ── Setters ───────────────────────────────────────────────────────────────
    public void setTestCaseId(String testCaseId)                       { this.testCaseId = testCaseId; }
    public void setTestCaseName(String testCaseName)                   { this.testCaseName = testCaseName; }
    public void setEndpoint(String endpoint)                           { this.endpoint = endpoint; }
    public void setMethod(String method)                               { this.method = method; }
    public void setRequestBody(String requestBody)                     { this.requestBody = requestBody; }
    public void setRequestParams(String requestParams)                 { this.requestParams = requestParams; }
    public void setExpectedStatusCode(String expectedStatusCode)       { this.expectedStatusCode = expectedStatusCode; }
    public void setExpectedResponseField(String expectedResponseField) { this.expectedResponseField = expectedResponseField; }
    public void setAssertionType(String assertionType)                 { this.assertionType = assertionType; }
    public void setTestType(String testType)                           { this.testType = testType; }
    public void setPriority(String priority)                           { this.priority = priority; }
    public void setDescription(String description)                     { this.description = description; }
    public void setAutomationFeasible(boolean automationFeasible)      { this.automationFeasible = automationFeasible; }

    @Override
    public String toString() {
        return "[" + testCaseId + "] " + testCaseName +
               " (" + method + " " + endpoint + ")";
    }
}