package com.saurav.agentic.models;

/**
 * TestCase - Represents a single UI test case generated by Agent 1
 * 
 */
public class TestCase {

    private String testCaseId;
    private String testCaseName;
    private String description;
    private String preconditions;
    private String testSteps;
    private String expectedResult;
    private String testType;
    private String priority;
    private String component;
    private boolean automationFeasible;

    public TestCase() {}

    // Getters
    public String getTestCaseId() { return testCaseId; }
    public String getTestCaseName() { return testCaseName; }
    public String getDescription() { return description; }
    public String getPreconditions() { return preconditions; }
    public String getTestSteps() { return testSteps; }
    public String getExpectedResult() { return expectedResult; }
    public String getTestType() { return testType; }
    public String getPriority() { return priority; }
    public String getComponent() { return component; }
    public boolean isAutomationFeasible() { return automationFeasible; }

    // Setters
    public void setTestCaseId(String testCaseId) { this.testCaseId = testCaseId; }
    public void setTestCaseName(String testCaseName) { this.testCaseName = testCaseName; }
    public void setDescription(String description) { this.description = description; }
    public void setPreconditions(String preconditions) { this.preconditions = preconditions; }
    public void setTestSteps(String testSteps) { this.testSteps = testSteps; }
    public void setExpectedResult(String expectedResult) { this.expectedResult = expectedResult; }
    public void setTestType(String testType) { this.testType = testType; }
    public void setPriority(String priority) { this.priority = priority; }
    public void setComponent(String component) { this.component = component; }
    public void setAutomationFeasible(boolean automationFeasible) { this.automationFeasible = automationFeasible; }

    @Override
    public String toString() {
        return "[" + testCaseId + "] " + testCaseName + " (" + testType + " | " + priority + ")";
    }
}