package com.saurav.agentic.agents;

import com.saurav.agentic.compiler.JavaCompilerUtil;
import com.saurav.agentic.constants.FrameworkConstants;
import com.saurav.agentic.models.CompileResult;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Agent3_Compiler - Compilation Verification Agent
 *
 * Compiles all generated Java files
 * Returns structured results for Agent 4 to fix
 */
public class Agent3_Compiler {

    private static final String PAGES_DIR   = "src/test/java/pages/";
    private static final String TESTS_DIR   = "src/test/java/generated/ui/";

    /**
     * Main entry point for Agent 3
     * Compiles all POM and Test files generated by Agent 2
     *
     * @param generatedClassNamesThisRun set of class names generated in current run
     * @return list of CompileResult — one per file, includes failures
     */
    public List<CompileResult> run(Set<String> generatedClassNamesThisRun) {

        System.out.println("\n" + FrameworkConstants.LOG_INFO +
                " ============================================");
        System.out.println(FrameworkConstants.LOG_INFO +
                " Agent 3: Compiler Started");
        System.out.println(FrameworkConstants.LOG_INFO +
                " ============================================");

        List<CompileResult> allResults = new ArrayList<>();

        // ── Step 1: Compile POM classes first ───────────────────────────────
        System.out.println(FrameworkConstants.LOG_INFO +
                " Compiling POM classes...");
        List<CompileResult> pomResults = JavaCompilerUtil.compileDirectory(PAGES_DIR);
        allResults.addAll(pomResults);

        // ── Step 2: Compile Test classes ────────────────────────────────────
        System.out.println("\n" + FrameworkConstants.LOG_INFO +
                " Compiling Test classes...");
        List<CompileResult> testResults = JavaCompilerUtil.compileDirectory(TESTS_DIR);
        allResults.addAll(testResults);

        // ── Step 3: Print summary ────────────────────────────────────────────
        printSummary(allResults, generatedClassNamesThisRun);

        return allResults;
    }

    private void printSummary(List<CompileResult> results, Set<String> generatedClassNamesThisRun) {
        long passed = results.stream().filter(CompileResult::isSuccess).count();
        long failed = results.stream().filter(r -> !r.isSuccess()).count();

        // Count NEW vs EXISTING for passed files
        long newThisRun = 0;
        long existingNotRegenerated = 0;

        for (CompileResult result : results) {
            if (result.isSuccess()) {
                String filePath = result.getFilePath();
                // Extract class name from file path (e.g., "src/test/java/pages/HomePage.java" -> "HomePage")
                if (filePath != null && filePath.contains(".java")) {
                    String fileName = filePath.substring(filePath.lastIndexOf("/") + 1, filePath.lastIndexOf(".java"));
                    if (generatedClassNamesThisRun.contains(fileName)) {
                        newThisRun++;
                    } else {
                        existingNotRegenerated++;
                    }
                }
            }
        }

        System.out.println("\n" + FrameworkConstants.LOG_INFO +
                " ============================================");
        System.out.println(FrameworkConstants.LOG_SUCCESS +
                " Agent 3 Complete!");
        System.out.println(FrameworkConstants.LOG_INFO +
                " Total files   : " + results.size());
        System.out.println(FrameworkConstants.LOG_INFO +
                " Compiled OK   : " + passed + " (New: " + newThisRun + ", Existing: " + existingNotRegenerated + ")");
        System.out.println(FrameworkConstants.LOG_INFO +
                " Failed        : " + failed);

        if (failed > 0) {
            System.out.println("\n" + FrameworkConstants.LOG_WARNING +
                    " Files with errors:");
            results.stream()
                   .filter(r -> !r.isSuccess())
                   .forEach(r -> {
                       System.out.println("   " + r.getFilePath());
                       r.getErrors().forEach(e ->
                           System.out.println("     → " + e));
                   });
        }

        System.out.println(FrameworkConstants.LOG_INFO +
                " ============================================\n");
    }
}